export const QUESTIONS = [
  {
    id: 1, ano: 2023, prova: "ENEM", area: "Ciências da Natureza", assunto: "Biologia - Genética",
    enunciado: "Em uma família, o pai apresenta daltonismo (herança ligada ao X, recessiva) e a mãe possui visão normal, mas é portadora do alelo para daltonismo. Qual a probabilidade de um filho do sexo masculino ser daltônico?",
    opcoes: [
      { letra: "A", texto: "0%" },
      { letra: "B", texto: "25%" },
      { letra: "C", texto: "50%" },
      { letra: "D", texto: "75%" },
      { letra: "E", texto: "100%" },
    ],
    correta: "C",
  },
  {
    id: 2, ano: 2022, prova: "ENEM", area: "Ciências Humanas", assunto: "História - Brasil Colônia",
    enunciado: "O sistema de sesmarias, adotado no Brasil colonial pelos portugueses, tinha como principal característica:",
    opcoes: [
      { letra: "A", texto: "A distribuição igualitária de terras entre colonos e indígenas." },
      { letra: "B", texto: "A concessão de grandes lotes de terra a quem se comprometesse a cultivá-los e defendê-los." },
      { letra: "C", texto: "A criação de propriedades comunais gerenciadas pela Coroa portuguesa." },
      { letra: "D", texto: "A venda de terras públicas para financiar expedições de exploração." },
      { letra: "E", texto: "A reserva de terras para a instalação exclusiva de missões jesuítas." },
    ],
    correta: "B",
  },
  {
    id: 3, ano: 2023, prova: "FUVEST", area: "Matemática", assunto: "Matemática - Geometria",
    enunciado: "Um círculo de raio r está inscrito em um triângulo equilátero. A área do triângulo, em função do raio r, é igual a:",
    opcoes: [
      { letra: "A", texto: "r²√3" },
      { letra: "B", texto: "3r²√3" },
      { letra: "C", texto: "2r²√3" },
      { letra: "D", texto: "r²√3 / 2" },
      { letra: "E", texto: "4r²√3" },
    ],
    correta: "B",
  },
  {
    id: 4, ano: 2022, prova: "ENEM", area: "Linguagens", assunto: "Literatura - Modernismo",
    enunciado: "A Semana de Arte Moderna de 1922, realizada em São Paulo, representou um marco na cultura brasileira principalmente porque:",
    opcoes: [
      { letra: "A", texto: "Consolidou o parnasianismo como escola literária dominante no Brasil." },
      { letra: "B", texto: "Buscou romper com os padrões estéticos europeus tradicionais e valorizar a identidade nacional." },
      { letra: "C", texto: "Promoveu a adoção exclusiva de temas religiosos nas artes plásticas brasileiras." },
      { letra: "D", texto: "Marcou o retorno ao realismo e ao naturalismo na literatura nacional." },
      { letra: "E", texto: "Estabeleceu normas gramaticais baseadas no português europeu clássico." },
    ],
    correta: "B",
  },
  {
    id: 5, ano: 2021, prova: "ENEM", area: "Ciências da Natureza", assunto: "Química - Termoquímica",
    enunciado: "Em uma reação química exotérmica, o que acontece com a entalpia do sistema?",
    opcoes: [
      { letra: "A", texto: "A entalpia aumenta, pois energia é liberada para o meio." },
      { letra: "B", texto: "A entalpia permanece constante, pois a energia total é conservada." },
      { letra: "C", texto: "A entalpia diminui, pois energia é liberada para o meio." },
      { letra: "D", texto: "A entalpia aumenta, pois o sistema absorve energia do meio." },
      { letra: "E", texto: "A entalpia diminui, pois o sistema absorve energia do meio." },
    ],
    correta: "C",
  },
  {
    id: 6, ano: 2020, prova: "ENEM", area: "Ciências Humanas", assunto: "Geografia - Geopolítica",
    enunciado: "O processo de globalização econômica intensificado a partir do final do século XX foi caracterizado principalmente por:",
    opcoes: [
      { letra: "A", texto: "Aumento das barreiras alfandegárias entre os países desenvolvidos." },
      { letra: "B", texto: "Redução da interdependência econômica entre as nações." },
      { letra: "C", texto: "Integração dos mercados financeiros e fluxo intenso de capitais, bens e serviços." },
      { letra: "D", texto: "Fortalecimento das economias nacionais em detrimento das multinacionais." },
      { letra: "E", texto: "Eliminação das desigualdades socioeconômicas entre países." },
    ],
    correta: "C",
  },
  {
    id: 7, ano: 2021, prova: "ENEM", area: "Matemática", assunto: "Matemática - Progressão Aritmética",
    enunciado: "Uma progressão aritmética tem primeiro termo a₁ = 3 e razão r = 4. Qual é o valor do 10º termo?",
    opcoes: [
      { letra: "A", texto: "37" },
      { letra: "B", texto: "39" },
      { letra: "C", texto: "40" },
      { letra: "D", texto: "43" },
      { letra: "E", texto: "47" },
    ],
    correta: "B",
  },
  {
    id: 8, ano: 2022, prova: "ENEM", area: "Ciências da Natureza", assunto: "Física - Cinemática",
    enunciado: "Um carro parte do repouso e acelera uniformemente a 2 m/s². Qual a velocidade do carro após 10 segundos?",
    opcoes: [
      { letra: "A", texto: "5 m/s" },
      { letra: "B", texto: "10 m/s" },
      { letra: "C", texto: "15 m/s" },
      { letra: "D", texto: "20 m/s" },
      { letra: "E", texto: "25 m/s" },
    ],
    correta: "D",
  },
  {
    id: 9, ano: 2019, prova: "ENEM", area: "Linguagens", assunto: "Língua Portuguesa - Interpretação de Texto",
    enunciado: "A norma-padrão da língua portuguesa é aquela que:",
    opcoes: [
      { letra: "A", texto: "É usada pela maioria da população brasileira no cotidiano." },
      { letra: "B", texto: "Está descrita em gramáticas e é ensinada nas escolas como referência formal." },
      { letra: "C", texto: "Elimina todas as variações regionais e sociais da língua." },
      { letra: "D", texto: "É exclusiva da comunicação oral em situações formais." },
      { letra: "E", texto: "Só se aplica à literatura erudita e à produção científica." },
    ],
    correta: "B",
  },
  {
    id: 10, ano: 2020, prova: "ENEM", area: "Ciências da Natureza", assunto: "Biologia - Ecologia",
    enunciado: "Qual das alternativas a seguir descreve corretamente o conceito de cadeia alimentar?",
    opcoes: [
      { letra: "A", texto: "Conjunto de organismos que competem pelo mesmo alimento em um ecossistema." },
      { letra: "B", texto: "Sequência linear de organismos em que cada um serve de alimento ao seguinte." },
      { letra: "C", texto: "Relação entre organismos de espécies diferentes que se beneficiam mutuamente." },
      { letra: "D", texto: "Ciclo de decomposição da matéria orgânica pelos fungos e bactérias." },
      { letra: "E", texto: "Conjunto de todas as populações que habitam um mesmo ecossistema." },
    ],
    correta: "B",
  },
  {
    id: 11, ano: 2021, prova: "ENEM", area: "Ciências Humanas", assunto: "Filosofia - Iluminismo",
    enunciado: "O Iluminismo foi um movimento intelectual europeu do século XVIII que defendia principalmente:",
    opcoes: [
      { letra: "A", texto: "A supremacia da fé religiosa sobre a razão humana." },
      { letra: "B", texto: "O retorno aos valores medievais e à autoridade da Igreja." },
      { letra: "C", texto: "O uso da razão como instrumento para questionar tradições e promover o progresso." },
      { letra: "D", texto: "A manutenção do absolutismo monárquico como forma de governo ideal." },
      { letra: "E", texto: "A valorização do misticismo e das práticas esotéricas." },
    ],
    correta: "C",
  },
  {
    id: 12, ano: 2022, prova: "ENEM", area: "Matemática", assunto: "Matemática - Função do 2º Grau",
    enunciado: "Dada a função f(x) = x² - 6x + 8, quais são as raízes da equação f(x) = 0?",
    opcoes: [
      { letra: "A", texto: "x = 1 e x = 8" },
      { letra: "B", texto: "x = 2 e x = 4" },
      { letra: "C", texto: "x = -2 e x = -4" },
      { letra: "D", texto: "x = 3 e x = 3" },
      { letra: "E", texto: "x = 0 e x = 6" },
    ],
    correta: "B",
  },
  {
    id: 13, ano: 2019, prova: "ENEM", area: "Ciências da Natureza", assunto: "Química - Ligações Químicas",
    enunciado: "A água (H₂O) possui ponto de ebulição muito mais alto do que seria esperado para uma molécula de massa molar tão baixa. Esse comportamento é explicado pela presença de:",
    opcoes: [
      { letra: "A", texto: "Ligações covalentes apolares entre os átomos de hidrogênio e oxigênio." },
      { letra: "B", texto: "Forças de London muito intensas entre as moléculas de água." },
      { letra: "C", texto: "Pontes de hidrogênio entre as moléculas de água." },
      { letra: "D", texto: "Ligações iônicas entre os átomos de hidrogênio e oxigênio." },
      { letra: "E", texto: "Forças de Van der Waals do tipo dipolo-dipolo induzido." },
    ],
    correta: "C",
  },
  {
    id: 14, ano: 2023, prova: "ENEM", area: "Ciências Humanas", assunto: "História - Ditadura Militar",
    enunciado: "O Ato Institucional nº 5 (AI-5), decretado em 1968 durante a ditadura militar brasileira, ficou conhecido como o 'golpe dentro do golpe' porque:",
    opcoes: [
      { letra: "A", texto: "Marcou o início do regime militar e a deposição do presidente João Goulart." },
      { letra: "B", texto: "Suspendeu direitos políticos, fechou o Congresso e eliminou garantias individuais, aprofundando a repressão." },
      { letra: "C", texto: "Determinou a realização de eleições diretas para presidente em 1969." },
      { letra: "D", texto: "Criou o sistema bipartidário com ARENA e MDB como únicos partidos permitidos." },
      { letra: "E", texto: "Estabeleceu a transição gradual para a democracia com a Lei de Anistia." },
    ],
    correta: "B",
  },
  {
    id: 15, ano: 2020, prova: "ENEM", area: "Matemática", assunto: "Matemática - Probabilidade",
    enunciado: "Uma urna contém 4 bolas vermelhas e 6 bolas azuis. Retirando-se uma bola ao acaso, qual a probabilidade de ela ser vermelha?",
    opcoes: [
      { letra: "A", texto: "1/4" },
      { letra: "B", texto: "2/5" },
      { letra: "C", texto: "3/5" },
      { letra: "D", texto: "4/6" },
      { letra: "E", texto: "1/2" },
    ],
    correta: "B",
  },
  {
    id: 16, ano: 2021, prova: "ENEM", area: "Linguagens", assunto: "Língua Portuguesa - Figuras de Linguagem",
    enunciado: "\"O tempo não para\" é um exemplo de qual figura de linguagem?",
    opcoes: [
      { letra: "A", texto: "Hipérbole" },
      { letra: "B", texto: "Eufemismo" },
      { letra: "C", texto: "Personificação (prosopopeia)" },
      { letra: "D", texto: "Antítese" },
      { letra: "E", texto: "Ironia" },
    ],
    correta: "C",
  },
  {
    id: 17, ano: 2022, prova: "ENEM", area: "Ciências da Natureza", assunto: "Biologia - Citologia",
    enunciado: "Qual organela celular é responsável pela produção de energia (ATP) nas células eucarióticas por meio da respiração celular aeróbica?",
    opcoes: [
      { letra: "A", texto: "Ribossomo" },
      { letra: "B", texto: "Retículo endoplasmático" },
      { letra: "C", texto: "Complexo de Golgi" },
      { letra: "D", texto: "Mitocôndria" },
      { letra: "E", texto: "Lisossomo" },
    ],
    correta: "D",
  },
  {
    id: 18, ano: 2019, prova: "ENEM", area: "Ciências Humanas", assunto: "Sociologia - Conceitos",
    enunciado: "O conceito de \"anomia\", desenvolvido por Émile Durkheim, refere-se a:",
    opcoes: [
      { letra: "A", texto: "A solidariedade mecânica presente em sociedades industrializadas." },
      { letra: "B", texto: "O estado de ausência ou enfraquecimento das normas sociais que regulam o comportamento dos indivíduos." },
      { letra: "C", texto: "A divisão do trabalho social que gera interdependência entre os indivíduos." },
      { letra: "D", texto: "O conflito de classes como motor da transformação histórica." },
      { letra: "E", texto: "A ação social orientada por valores tradicionais e religiosos." },
    ],
    correta: "B",
  },
  {
    id: 19, ano: 2021, prova: "FUVEST", area: "Ciências da Natureza", assunto: "Física - Termodinâmica",
    enunciado: "Uma máquina térmica absorve 800 J de calor da fonte quente e realiza 300 J de trabalho. Qual é o rendimento dessa máquina?",
    opcoes: [
      { letra: "A", texto: "25,5%" },
      { letra: "B", texto: "32,5%" },
      { letra: "C", texto: "37,5%" },
      { letra: "D", texto: "42,5%" },
      { letra: "E", texto: "50%" },
    ],
    correta: "C",
  },
  {
    id: 20, ano: 2020, prova: "ENEM", area: "Linguagens", assunto: "Literatura - Romantismo",
    enunciado: "O Romantismo brasileiro, na sua primeira geração, tinha como característica central:",
    opcoes: [
      { letra: "A", texto: "A crítica social intensa e o retrato da pobreza urbana." },
      { letra: "B", texto: "A exaltação da natureza nacional e do índio como símbolo da identidade brasileira." },
      { letra: "C", texto: "O pessimismo e o questionamento filosófico da existência humana." },
      { letra: "D", texto: "O realismo na descrição dos costumes da burguesia oitocentista." },
      { letra: "E", texto: "A valorização da métrica clássica e da razão iluminista." },
    ],
    correta: "B",
  },
  {
    id: 21, ano: 2022, prova: "ENEM", area: "Ciências da Natureza", assunto: "Química - PH e Ácidos",
    enunciado: "Uma solução aquosa com pH = 3 é considerada:",
    opcoes: [
      { letra: "A", texto: "Básica, pois o pH é inferior a 7." },
      { letra: "B", texto: "Neutra, pois o pH está próximo de 7." },
      { letra: "C", texto: "Ácida, pois o pH é inferior a 7." },
      { letra: "D", texto: "Básica, pois quanto menor o pH, mais básica a solução." },
      { letra: "E", texto: "Neutra, pois o pH só é ácido abaixo de 1." },
    ],
    correta: "C",
  },
  {
    id: 22, ano: 2021, prova: "ENEM", area: "Ciências Humanas", assunto: "Geografia - Climatologia",
    enunciado: "O fenômeno El Niño é caracterizado pelo:",
    opcoes: [
      { letra: "A", texto: "Resfriamento anormal das águas superficiais do Oceano Pacífico equatorial." },
      { letra: "B", texto: "Aquecimento anormal das águas superficiais do Oceano Atlântico Sul." },
      { letra: "C", texto: "Aquecimento anormal das águas superficiais do Oceano Pacífico equatorial." },
      { letra: "D", texto: "Aumento das correntes de ar frio provenientes do Polo Sul." },
      { letra: "E", texto: "Diminuição da evaporação nos oceanos tropicais." },
    ],
    correta: "C",
  },
  {
    id: 23, ano: 2023, prova: "ENEM", area: "Matemática", assunto: "Matemática - Logaritmos",
    enunciado: "Se log₂(x) = 5, qual é o valor de x?",
    opcoes: [
      { letra: "A", texto: "10" },
      { letra: "B", texto: "16" },
      { letra: "C", texto: "25" },
      { letra: "D", texto: "32" },
      { letra: "E", texto: "64" },
    ],
    correta: "D",
  },
  {
    id: 24, ano: 2020, prova: "ENEM", area: "Ciências da Natureza", assunto: "Biologia - Evolução",
    enunciado: "Segundo a teoria sintética da evolução (Neodarwinismo), os mecanismos responsáveis pela evolução das espécies são:",
    opcoes: [
      { letra: "A", texto: "Uso e desuso dos órgãos e herança dos caracteres adquiridos." },
      { letra: "B", texto: "Seleção natural, mutação, deriva genética e fluxo gênico." },
      { letra: "C", texto: "Apenas a seleção natural, sem influência de fatores genéticos." },
      { letra: "D", texto: "A vontade dos organismos de se adaptarem ao ambiente." },
      { letra: "E", texto: "A pressão do ambiente sobre as características adquiridas ao longo da vida." },
    ],
    correta: "B",
  },
  {
    id: 25, ano: 2019, prova: "ENEM", area: "Linguagens", assunto: "Redação - Dissertação Argumentativa",
    enunciado: "Na redação dissertativa-argumentativa do ENEM, a proposta de intervenção deve obrigatoriamente:",
    opcoes: [
      { letra: "A", texto: "Conter apenas críticas ao governo federal sobre o tema abordado." },
      { letra: "B", texto: "Apresentar uma solução para o problema com agente, ação, modo/meio, efeito e detalhamento." },
      { letra: "C", texto: "Reproduzir fielmente dados estatísticos citados nos textos da prova." },
      { letra: "D", texto: "Ser escrita em primeira pessoa do singular para demonstrar engajamento pessoal." },
      { letra: "E", texto: "Ocupar pelo menos dois parágrafos da redação para garantir a nota máxima." },
    ],
    correta: "B",
  },
  {
    id: 26, ano: 2022, prova: "ENEM", area: "Ciências Humanas", assunto: "História - Abolição da Escravidão",
    enunciado: "A Lei Áurea, assinada em 13 de maio de 1888 pela Princesa Isabel, aboliu a escravidão no Brasil. Porém, historiadores criticam a simples celebração desta data porque:",
    opcoes: [
      { letra: "A", texto: "A lei foi resultado exclusivo da pressão militar sobre a monarquia." },
      { letra: "B", texto: "A abolição foi acompanhada de políticas de reparação e integração dos ex-escravizados à sociedade." },
      { letra: "C", texto: "A lei não foi acompanhada de políticas de integração social, deixando os ex-escravizados sem terra, emprego ou apoio do Estado." },
      { letra: "D", texto: "A escravidão continuou legal nas fazendas de café por mais uma década." },
      { letra: "E", texto: "O Brasil foi o primeiro país das Américas a abolir a escravidão formalmente." },
    ],
    correta: "C",
  },
  {
    id: 27, ano: 2021, prova: "ENEM", area: "Ciências da Natureza", assunto: "Física - Eletrostática",
    enunciado: "Dois corpos condutores com cargas elétricas Q₁ = +4 μC e Q₂ = -2 μC são colocados em contato e depois separados. Qual a carga de cada corpo após o contato?",
    opcoes: [
      { letra: "A", texto: "+4 μC e -2 μC (permanecem iguais)" },
      { letra: "B", texto: "+1 μC e +1 μC" },
      { letra: "C", texto: "+2 μC e 0 μC" },
      { letra: "D", texto: "+3 μC e -1 μC" },
      { letra: "E", texto: "0 μC e +2 μC" },
    ],
    correta: "B",
  },
  {
    id: 28, ano: 2020, prova: "ENEM", area: "Matemática", assunto: "Matemática - Trigonometria",
    enunciado: "Em um triângulo retângulo, o seno do ângulo α é igual a 3/5. Qual é o cosseno de α?",
    opcoes: [
      { letra: "A", texto: "3/4" },
      { letra: "B", texto: "4/5" },
      { letra: "C", texto: "5/3" },
      { letra: "D", texto: "1/5" },
      { letra: "E", texto: "5/4" },
    ],
    correta: "B",
  },
  {
    id: 29, ano: 2023, prova: "ENEM", area: "Linguagens", assunto: "Literatura - Realismo",
    enunciado: "Dom Casmurro, de Machado de Assis, é considerado um clássico do Realismo brasileiro principalmente porque:",
    opcoes: [
      { letra: "A", texto: "Apresenta um narrador onisciente e imparcial que descreve objetivamente a realidade social." },
      { letra: "B", texto: "Narra as aventuras românticas de um herói idealizado em meio à natureza brasileira." },
      { letra: "C", texto: "Traz um narrador em primeira pessoa não confiável, com análise psicológica profunda dos personagens." },
      { letra: "D", texto: "Defende abertamente causas abolicionistas e republicanas no contexto histórico do Segundo Reinado." },
      { letra: "E", texto: "Usa linguagem popular e valoriza os costumes regionais do interior do Brasil." },
    ],
    correta: "C",
  },
  {
    id: 30, ano: 2019, prova: "ENEM", area: "Ciências da Natureza", assunto: "Química - Reações Orgânicas",
    enunciado: "A fermentação alcoólica, processo utilizado na produção de bebidas e biocombustíveis, converte glicose em:",
    opcoes: [
      { letra: "A", texto: "Ácido lático e dióxido de carbono." },
      { letra: "B", texto: "Etanol e dióxido de carbono." },
      { letra: "C", texto: "Acetona e água." },
      { letra: "D", texto: "Metanol e oxigênio." },
      { letra: "E", texto: "Ácido acético e hidrogênio." },
    ],
    correta: "B",
  },
]

export const AREAS = ["Todas", "Ciências da Natureza", "Ciências Humanas", "Matemática", "Linguagens"]
export const PROVAS = ["Todas", "ENEM", "FUVEST"]
